import { AIProvider } from './provider.interface.js';
import { AIResponse, ConversationContext } from '@pulsebi/shared-types';
import { logger } from '../utils/logger.js';

export class OllamaProvider implements AIProvider {
  public async generateSummary(_statisticsContext: Record<string, any>): Promise<string> {
    logger.info("Ollama summary request");
    return 'This is a mock business summary generated by the Ollama AI provider.';
  }

  public async answerQuestion(question: string, _context: ConversationContext): Promise<string> {
    logger.info({ question }, 'OllamaProvider.answerQuestion called');
    return `This is a mock answer to your question: "${question}"`;
  }

  public async generateDashboardAction(question: string, _context: ConversationContext): Promise<AIResponse> {
    logger.info({ question }, 'OllamaProvider.generateDashboardAction called');
    return {
      answer: `I've processed your query: "${question}"`,
      actions: [],
    };
  }

  public async generateRecommendations(_statisticsContext: Record<string, any>): Promise<string[]> {
    logger.info('OllamaProvider.generateRecommendations called');
    return [
      'What was the monthly revenue trend?',
      'Which product generated the highest profit?',
      'Compare Q1 and Q2 sales performance.',
    ];
  }
}
